on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3.5.1
        with:
          cache: yarn
          node-version-file: .nvmrc

      - run: yarn install --immutable

      - run: rm node_modules/@mui/joy/*/package.json

      - run: yarn run check
        env:
          DEBUG: "typescript-eslint:*"
